version: '2.3'
services:
    mysql:
        image: vulhub/mysql:5.5.23
        container_name: mysql_container
        ports:
            - '2000:3306'
        networks:
            vuln-microservice-app:
                ipv4_address: 172.22.0.2

    react-frontend:
        container_name: react-frontend_container
        image: react-frontend
        build:
            context: ./frontend
            target: development
        volumes:
            - ./frontend/src:/frontend/src
        ports:
            - '3000:3000'
        # command: ['npm', 'run', 'dev']

    ping:
        image: ping
        container_name: ping_container
        build:
            context: ./ping
            dockerfile: Dockerfile
        ports:
            - '8081:8081'
        cap_add:
            - SYS_ADMIN
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        privileged: true
        networks:
            vuln-microservice-app:
                ipv4_address: 172.22.0.3
        volumes:
            - /:/host

    sql-inject:
        image: sql-inject
        container_name: sql-inject_container
        build:
            context: ./sql-injection
            dockerfile: Dockerfile
        ports:
            - '8082:8082'
        networks:
            vuln-microservice-app:
                ipv4_address: 172.22.0.4

    file-upload:
        image: file-upload
        container_name: file-upload_container
        build:
            context: ./file-upload
            dockerfile: Dockerfile
        ports:
            - '8083:8083'
        networks:
            vuln-microservice-app:
                ipv4_address: 172.22.0.5

    xss_r:
        image: xss_r
        container_name: xss-r_container
        build:
            context: ./xss_r
            dockerfile: Dockerfile
        ports:
            - '8084:8084'
        networks:
            vuln-microservice-app:
                ipv4_address: 172.22.0.6

#  ping-gvisor:
#    build: ping
#    runtime: "runsc"
#    ports:
#     - "8083:8083"
#    cap_add:
#     - SYS_ADMIN
#    security_opt:
#     - apparmour:unconfined

networks:
    vuln-microservice-app:
        ipam:
            config:
                - subnet: 172.22.0.0/24
