FROM ubuntu:20.04
WORKDIR /exploit

# Install all dependencies
RUN apt update
RUN apt install perl
ADD https://sourceforge.net/projects/nfsen/files/stable/nfsen-1.3.7/nfsen-1.3.7.tar.gz/download /exploit/

CMD ["/bin/bash"]