mkdir data
docker exec -it dockercomposemanifests_ts-news-mongo_1 sh -c "pmap 1" > data/ts-news-mongo.txt             
docker exec -it dockercomposemanifests_ts-consign-price-mongo_1 sh -c "pmap 1" > data/ts-consign-price-mongo.txt  
docker exec -it dockercomposemanifests_ts-route-mongo_1 sh -c "pmap 1" > data/ts-route-mongo.txt 
docker exec -it dockercomposemanifests_ts-basic-service_1 sh -c "pmap 1" > data/ts-basic-service.txt 
docker exec -it dockercomposemanifests_ts-ticket-office-service_1 sh -c "pmap 1" > data/ts-ticket-office-service.txt 
docker exec -it dockercomposemanifests_ts-rebook-service_1 sh -c "pmap 1" > data/ts-rebook-service.txt 
docker exec -it dockercomposemanifests_ts-user-service_1 sh -c "pmap 1" > data/ts-user-service.txt      
docker exec -it dockercomposemanifests_ts-preserve-service_1 sh -c "pmap 1" > data/ts-preserve-service.txt  
docker exec -it dockercomposemanifests_ts-admin-route-service_1 sh -c "pmap 1" > data/ts-admin-route-service.txt  
docker exec -it dockercomposemanifests_ts-station-service_1 sh -c "pmap 1" > data/ts-station-service.txt    
docker exec -it dockercomposemanifests_ts-price-service_1 sh -c "pmap 1" > data/ts-price-service.txt  
docker exec -it dockercomposemanifests_ts-contacts-service_1 sh -c "pmap 1" > data/ts-contacts-service.txt  
docker exec -it dockercomposemanifests_ts-station-mongo_1 sh -c "pmap 1" > data/ts-station-mongo.txt       
docker exec -it dockercomposemanifests_ts-security-mongo_1 sh -c "pmap 1" > data/ts-security-mongo.txt  
docker exec -it dockercomposemanifests_ts-voucher-service_1 sh -c "pmap 1" > data/ts-voucher-service.txt            
docker exec -it dockercomposemanifests_ts-news-service_1 sh -c "pmap 1" > data/ts-news-service.txt               
docker exec -it dockercomposemanifests_ts-assurance-mongo_1 sh -c "pmap 1" > data/ts-assurance-mongo.txt            
docker exec -it dockercomposemanifests_ts-travel-mongo_1 sh -c "pmap 1" > data/ts-travel-mongo.txt           
docker exec -it dockercomposemanifests_ts-admin-order-service_1 sh -c "pmap 1" > data/ts-admin-order-service.txt        
docker exec -it dockercomposemanifests_ts-auth-mongo_1 sh -c "pmap 1" > data/ts-auth-mongo.txt                 
docker exec -it dockercomposemanifests_ts-route-service_1 sh -c "pmap 1" > data/ts-route-service.txt              
docker exec -it dockercomposemanifests_ts-consign-mongo_1 sh -c "pmap 1" > data/ts-consign-mongo.txt              
docker exec -it dockercomposemanifests_ts-route-plan-service_1 sh -c "pmap 1" > data/ts-route-plan-service.txt         
docker exec -it dockercomposemanifests_ts-food-map-service_1 sh -c "pmap 1" > data/ts-food-map-service.txt           
docker exec -it dockercomposemanifests_ts-admin-user-service_1 sh -c "pmap 1" > data/ts-admin-user-service.txt         
docker exec -it dockercomposemanifests_ts-train-service_1 sh -c "pmap 1" > data/ts-train-service.txt              
docker exec -it dockercomposemanifests_ts-order-service_1 sh -c "pmap 1" > data/ts-order-service.txt              
docker exec -it dockercomposemanifests_ts-travel2-service_1 sh -c "pmap 1" > data/ts-travel2-service.txt        
docker exec -it dockercomposemanifests_ts-ticket-office-mongo_1 sh -c "pmap 1" > data/ts-ticket-office-mongo.txt        
docker exec -it dockercomposemanifests_ts-contacts-mongo_1 sh -c "pmap 1" > data/ts-contacts-mongo.txt             
docker exec -it dockercomposemanifests_ts-ticketinfo-service_1 sh -c "pmap 1" > data/ts-ticketinfo-service.txt         
docker exec -it dockercomposemanifests_ts-travel-service_1 sh -c "pmap 1" > data/ts-travel-service.txt             
docker exec -it dockercomposemanifests_ts-food-service_1 sh -c "pmap 1" > data/ts-food-service.txt               
docker exec -it dockercomposemanifests_ts-ui-dashboard_1 sh -c "pmap 1" > data/ts-ui-dashboard.txt               
docker exec -it dockercomposemanifests_jaeger_1 sh -c "pmap 1" > data/jaeger.txt                        
docker exec -it dockercomposemanifests_ts-travel-plan-service_1 sh -c "pmap 1" > data/ts-travel-plan-service.txt        
docker exec -it dockercomposemanifests_ts-consign-price-service_1 sh -c "pmap 1" > data/ts-consign-price-service.txt      
docker exec -it dockercomposemanifests_ts-seat-service_1 sh -c "pmap 1" > data/ts-seat-service.txt               
docker exec -it dockercomposemanifests_ts-order-mongo_1 sh -c "pmap 1" > data/ts-order-mongo.txt                
docker exec -it dockercomposemanifests_ts-travel2-mongo_1 sh -c "pmap 1" > data/ts-travel2-mongo.txt              
docker exec -it dockercomposemanifests_ts-verification-code-service_1 sh -c "pmap 1" > data/ts-verification-code-service.txt  
docker exec -it dockercomposemanifests_ts-price-mongo_1 sh -c "pmap 1" > data/ts-price-mongo.txt                
docker exec -it dockercomposemanifests_ts-order-other-mongo_1 sh -c "pmap 1" > data/ts-order-other-mongo.txt          
docker exec -it dockercomposemanifests_ts-order-other-service_1 sh -c "pmap 1" > data/ts-order-other-service.txt        
docker exec -it dockercomposemanifests_ts-admin-basic-info-service_1 sh -c "pmap 1" > data/ts-admin-basic-info-service.txt   
docker exec -it dockercomposemanifests_ts-voucher-mysql_1 sh -c "pmap 1" > data/ts-voucher-mysql.txt              
docker exec -it dockercomposemanifests_ts-account-mongo_1 sh -c "pmap 1" > data/ts-account-mongo.txt              
docker exec -it dockercomposemanifests_ts-config-service_1 sh -c "pmap 1" > data/ts-config-service.txt             
docker exec -it dockercomposemanifests_ts-auth-service_1 sh -c "pmap 1" > data/ts-auth-service.txt               
docker exec -it dockercomposemanifests_ts-cancel-service_1 sh -c "pmap 1" > data/ts-cancel-service.txt             
docker exec -it dockercomposemanifests_ts-payment-service_1 sh -c "pmap 1" > data/ts-payment-service.txt            
docker exec -it dockercomposemanifests_ts-train-mongo_1 sh -c "pmap 1" > data/ts-train-mongo.txt                
docker exec -it dockercomposemanifests_ts-execute-service_1 sh -c "pmap 1" > data/ts-execute-service.txt            
docker exec -it dockercomposemanifests_ts-consign-service_1 sh -c "pmap 1" > data/ts-consign-service.txt            
docker exec -it dockercomposemanifests_ts-rebook-mongo_1 sh -c "pmap 1" > data/ts-rebook-mongo.txt               
docker exec -it dockercomposemanifests_ts-assurance-service_1 sh -c "pmap 1" > data/ts-assurance-service.txt          
docker exec -it dockercomposemanifests_ts-config-mongo_1 sh -c "pmap 1" > data/ts-config-mongo.txt               
docker exec -it dockercomposemanifests_ts-preserve-other-service_1 sh -c "pmap 1" > data/ts-preserve-other-service.txt     
docker exec -it dockercomposemanifests_ts-food-map-mongo_1 sh -c "pmap 1" > data/ts-food-map-mongo.txt             
docker exec -it dockercomposemanifests_ts-user-mongo_1 sh -c "pmap 1" > data/ts-user-mongo.txt                 
docker exec -it dockercomposemanifests_ts-admin-travel-service_1 sh -c "pmap 1" > data/ts-admin-travel-service.txt       
docker exec -it dockercomposemanifests_ts-payment-mongo_1 sh -c "pmap 1" > data/ts-payment-mongo.txt              
docker exec -it dockercomposemanifests_ts-inside-payment-service_1 sh -c "pmap 1" > data/ts-inside-payment-service.txt     
docker exec -it dockercomposemanifests_redis_1 sh -c "pmap 1" > data/redis.txt                         
docker exec -it dockercomposemanifests_ts-security-service_1 sh -c "pmap 1" > data/ts-security-service.txt           
docker exec -it dockercomposemanifests_ts-food-mongo_1 sh -c "pmap 1" > data/ts-food-mongo.txt                 
docker exec -it dockercomposemanifests_ts-inside-payment-mongo_1 sh -c "pmap 1" > data/ts-inside-payment-mongo.txt       