mkdir pmap
docker exec -it dockercomposemanifests_ts-voucher-service_1 sh -c "pmap -p 1" > pmap/voucher-service.txt
docker exec -it dockercomposemanifests_ts-train-mongo_1 sh -c "pmap -p 1" > pmap/train-mongo.txt
docker exec -it dockercomposemanifests_ts-ticket-office-service_1 sh -c "pmap -p 1" > pmap/ticket-office-service.txt
docker exec -it dockercomposemanifests_ts-order-other-service_1 sh -c "pmap -p 1" > pmap/order-other-service.txt
docker exec -it dockercomposemanifests_redis_1 sh -c "pmap -p 1" > pmap/redis.txt
docker exec -it dockercomposemanifests_ts-travel-service_1 sh -c "pmap -p 1" > pmap/travel-service.txt
docker exec -it dockercomposemanifests_ts-rebook-service_1 sh -c "pmap -p 1" > pmap/rebook-service.txt
docker exec -it dockercomposemanifests_ts-news-mongo_1 sh -c "pmap -p 1" > pmap/news-mongo.txt
docker exec -it dockercomposemanifests_ts-consign-service_1 sh -c "pmap -p 1" > pmap/consign-service.txt
docker exec -it dockercomposemanifests_ts-food-map-service_1 sh -c "pmap -p 1" > pmap/food-map-service.txt
docker exec -it dockercomposemanifests_ts-account-mongo_1 sh -c "pmap -p 1" > pmap/account-mongo.txt
docker exec -it dockercomposemanifests_ts-admin-basic-info-service_1 sh -c "pmap -p 1" > pmap/admin-basic-info-service.txt
docker exec -it dockercomposemanifests_ts-travel2-service_1 sh -c "pmap -p 1" > pmap/travel2-service.txt
docker exec -it dockercomposemanifests_ts-cancel-service_1 sh -c "pmap -p 1" > pmap/cancel-service.txt
docker exec -it dockercomposemanifests_ts-inside-payment-service_1 sh -c "pmap -p 1" > pmap/inside-payment-service.txt
docker exec -it dockercomposemanifests_ts-news-service_1 sh -c "pmap -p 1" > pmap/news-service.txt
docker exec -it dockercomposemanifests_ts-assurance-mongo_1 sh -c "pmap -p 1" > pmap/assurance-mongo.txt
docker exec -it dockercomposemanifests_ts-admin-route-service_1 sh -c "pmap -p 1" > pmap/admin-route-service.txt
docker exec -it dockercomposemanifests_ts-ticketinfo-service_1 sh -c "pmap -p 1" > pmap/ticketinfo-service.txt
docker exec -it dockercomposemanifests_ts-security-service_1 sh -c "pmap -p 1" > pmap/security-service.txt
docker exec -it dockercomposemanifests_ts-consign-price-service_1 sh -c "pmap -p 1" > pmap/consign-price-service.txt
docker exec -it dockercomposemanifests_ts-config-service_1 sh -c "pmap -p 1" > pmap/config-service.txt
docker exec -it dockercomposemanifests_ts-user-service_1 sh -c "pmap -p 1" > pmap/user-service.txt
docker exec -it dockercomposemanifests_ts-config-mongo_1 sh -c "pmap -p 1" > pmap/config-mongo.txt
docker exec -it dockercomposemanifests_ts-verification-code-service_1 sh -c "pmap -p 1" > pmap/verification-code-service.txt
docker exec -it dockercomposemanifests_ts-food-service_1 sh -c "pmap -p 1" > pmap/food-service.txt
docker exec -it dockercomposemanifests_ts-admin-user-service_1 sh -c "pmap -p 1" > pmap/admin-user-service.txt
docker exec -it dockercomposemanifests_ts-inside-payment-mongo_1 sh -c "pmap -p 1" > pmap/inside-payment-mongo.txt
docker exec -it dockercomposemanifests_ts-train-service_1 sh -c "pmap -p 1" > pmap/train-service.txt
docker exec -it dockercomposemanifests_ts-order-service_1 sh -c "pmap -p 1" > pmap/order-service.txt
docker exec -it dockercomposemanifests_ts-rebook-mongo_1 sh -c "pmap -p 1" > pmap/rebook-mongo.txt
docker exec -it dockercomposemanifests_ts-ui-dashboard_1 sh -c "pmap -p 1" > pmap/ui-dashboard.txt
docker exec -it dockercomposemanifests_ts-admin-travel-service_1 sh -c "pmap -p 1" > pmap/admin-travel-service.txt
docker exec -it dockercomposemanifests_ts-admin-order-service_1 sh -c "pmap -p 1" > pmap/admin-order-service.txt
docker exec -it dockercomposemanifests_ts-consign-price-mongo_1 sh -c "pmap -p 1" > pmap/consign-price-mongo.txt
docker exec -it dockercomposemanifests_ts-auth-service_1 sh -c "pmap -p 1" > pmap/auth-service.txt
docker exec -it dockercomposemanifests_ts-assurance-service_1 sh -c "pmap -p 1" > pmap/assurance-service.txt
docker exec -it dockercomposemanifests_ts-route-plan-service_1 sh -c "pmap -p 1" > pmap/route-plan-service.txt
docker exec -it dockercomposemanifests_ts-travel-plan-service_1 sh -c "pmap -p 1" > pmap/travel-plan-service.txt
docker exec -it dockercomposemanifests_ts-price-mongo_1 sh -c "pmap -p 1" > pmap/price-mongo.txt
docker exec -it dockercomposemanifests_ts-route-mongo_1 sh -c "pmap -p 1" > pmap/route-mongo.txt
docker exec -it dockercomposemanifests_ts-food-mongo_1 sh -c "pmap -p 1" > pmap/food-mongo.txt
docker exec -it dockercomposemanifests_ts-preserve-service_1 sh -c "pmap -p 1" > pmap/preserve-service.txt
docker exec -it dockercomposemanifests_ts-user-mongo_1 sh -c "pmap -p 1" > pmap/user-mongo.txt
docker exec -it dockercomposemanifests_ts-ticket-office-mongo_1 sh -c "pmap -p 1" > pmap/ticket-office-mongo.txt
docker exec -it dockercomposemanifests_ts-basic-service_1 sh -c "pmap -p 1" > pmap/basic-service.txt
docker exec -it dockercomposemanifests_ts-contacts-mongo_1 sh -c "pmap -p 1" > pmap/contacts-mongo.txt
docker exec -it dockercomposemanifests_ts-food-map-mongo_1 sh -c "pmap -p 1" > pmap/food-map-mongo.txt
docker exec -it dockercomposemanifests_ts-payment-service_1 sh -c "pmap -p 1" > pmap/payment-service.txt
docker exec -it dockercomposemanifests_ts-consign-mongo_1 sh -c "pmap -p 1" > pmap/consign-mongo.txt
docker exec -it dockercomposemanifests_ts-security-mongo_1 sh -c "pmap -p 1" > pmap/security-mongo.txt
docker exec -it dockercomposemanifests_ts-price-service_1 sh -c "pmap -p 1" > pmap/price-service.txt
docker exec -it dockercomposemanifests_ts-contacts-service_1 sh -c "pmap -p 1" > pmap/contacts-service.txt
docker exec -it dockercomposemanifests_ts-route-service_1 sh -c "pmap -p 1" > pmap/route-service.txt
docker exec -it dockercomposemanifests_ts-notification-service_1 sh -c "pmap -p 1" > pmap/notification-service.txt
docker exec -it dockercomposemanifests_ts-station-service_1 sh -c "pmap -p 1" > pmap/station-service.txt
docker exec -it dockercomposemanifests_ts-payment-mongo_1 sh -c "pmap -p 1" > pmap/payment-mongo.txt
docker exec -it dockercomposemanifests_ts-station-mongo_1 sh -c "pmap -p 1" > pmap/station-mongo.txt
docker exec -it dockercomposemanifests_ts-travel2-mongo_1 sh -c "pmap -p 1" > pmap/travel2-mongo.txt
docker exec -it dockercomposemanifests_ts-seat-service_1 sh -c "pmap -p 1" > pmap/seat-service.txt
docker exec -it dockercomposemanifests_ts-order-other-mongo_1 sh -c "pmap -p 1" > pmap/order-other-mongo.txt
docker exec -it dockercomposemanifests_ts-preserve-other-service_1 sh -c "pmap -p 1" > pmap/preserve-other-service.txt
docker exec -it dockercomposemanifests_ts-auth-mongo_1 sh -c "pmap -p 1" > pmap/auth-mongo.txt
docker exec -it dockercomposemanifests_ts-execute-service_1 sh -c "pmap -p 1" > pmap/execute-service.txt